version: '3.8'
name: petamin
services:
  petamin_postgres:
    image: postgres
    container_name: petamin_postgres
    ports:
      - 54321:5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "petamin" ]
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      POSTGRES_PASSWORD: petamin
      POSTGRES_USER: petamin
      POSTGRES_DB: petamin
  petamin_minio:
    image: bitnami/minio:latest
    container_name: petamin_minio
    ports:
      - 9000:9000
      - 9001:9001
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      MINIO_ACCESS_KEY: petamin
      MINIO_SECRET_KEY: petamin
      MINIO_ROOT_USER: petamin-user
      MINIO_ROOT_PASSWORD: petamin-password
      MINIO_BROWSER: "on"
