version: '3.8'
name: petamin_dev
services:
  petamin_postgres:
    image: postgres:14-alpine
    container_name: petamin_postgres_dev
    ports:
      - 54321:5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "petamin" ]
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      POSTGRES_PASSWORD: petamin
      POSTGRES_USER: petamin
      POSTGRES_DB: petamin